// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_providers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAuthProvider = `-- name: CreateAuthProvider :one
INSERT INTO auth_providers (
    user_id,
    provider,
    provider_user_id
) VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_user_id, created_at, updated_at
`

type CreateAuthProviderParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
}

func (q *Queries) CreateAuthProvider(ctx context.Context, arg CreateAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRowContext(ctx, createAuthProvider, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthProvider = `-- name: DeleteAuthProvider :exec
DELETE FROM auth_providers
WHERE id = $1
`

func (q *Queries) DeleteAuthProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAuthProvider, id)
	return err
}

const getAuthProvider = `-- name: GetAuthProvider :one
SELECT id, user_id, provider, provider_user_id, created_at, updated_at FROM auth_providers
WHERE provider = $1 AND provider_user_id = $2
`

type GetAuthProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetAuthProvider(ctx context.Context, arg GetAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRowContext(ctx, getAuthProvider, arg.Provider, arg.ProviderUserID)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthProvidersByUserID = `-- name: GetAuthProvidersByUserID :many
SELECT id, user_id, provider, provider_user_id, created_at, updated_at FROM auth_providers
WHERE user_id = $1
`

func (q *Queries) GetAuthProvidersByUserID(ctx context.Context, userID uuid.UUID) ([]AuthProvider, error) {
	rows, err := q.db.QueryContext(ctx, getAuthProvidersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthProvider
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
