// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
    id,
    created_at,
    updated_at,
    name,
    description,
    primary_muscle_group,
    secondary_muscle_group
) VALUES (
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2,
    $3,
    $4
) RETURNING id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at
`

type CreateExerciseParams struct {
	Name                 string
	Description          sql.NullString
	PrimaryMuscleGroup   sql.NullString
	SecondaryMuscleGroup sql.NullString
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise,
		arg.Name,
		arg.Description,
		arg.PrimaryMuscleGroup,
		arg.SecondaryMuscleGroup,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrimaryMuscleGroup,
		&i.SecondaryMuscleGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises
WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExercise, id)
	return err
}

const getAllExercises = `-- name: GetAllExercises :many
SELECT id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at FROM exercises
`

func (q *Queries) GetAllExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getAllExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PrimaryMuscleGroup,
			&i.SecondaryMuscleGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMuscleGroups = `-- name: GetAllMuscleGroups :many
SELECT DISTINCT muscle_group
FROM (
    SELECT primary_muscle_group AS muscle_group FROM exercises
    UNION
    SELECT secondary_muscle_group AS muscle_group FROM exercises
) AS all_groups
WHERE muscle_group IS NOT NULL
ORDER BY muscle_group
`

func (q *Queries) GetAllMuscleGroups(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getAllMuscleGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var muscle_group sql.NullString
		if err := rows.Scan(&muscle_group); err != nil {
			return nil, err
		}
		items = append(items, muscle_group)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at FROM exercises
WHERE id = $1
`

func (q *Queries) GetExerciseByID(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrimaryMuscleGroup,
		&i.SecondaryMuscleGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExerciseByKeyword = `-- name: GetExerciseByKeyword :many
SELECT id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at FROM exercises
WHERE
    concat(name, ' ', primary_muscle_group, ' ', secondary_muscle_group)
    ILIKE '%' || $1::text || '%'
`

func (q *Queries) GetExerciseByKeyword(ctx context.Context, word string) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseByKeyword, word)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PrimaryMuscleGroup,
			&i.SecondaryMuscleGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseByName = `-- name: GetExerciseByName :one
SELECT id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at FROM exercises
WHERE name = $1
`

func (q *Queries) GetExerciseByName(ctx context.Context, name string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByName, name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrimaryMuscleGroup,
		&i.SecondaryMuscleGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExercisesByPrimaryMG = `-- name: GetExercisesByPrimaryMG :many
SELECT id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at FROM exercises
WHERE primary_muscle_group = $1
`

func (q *Queries) GetExercisesByPrimaryMG(ctx context.Context, primaryMuscleGroup sql.NullString) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getExercisesByPrimaryMG, primaryMuscleGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PrimaryMuscleGroup,
			&i.SecondaryMuscleGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExercisesBySecondaryMG = `-- name: GetExercisesBySecondaryMG :many
SELECT id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at FROM exercises
WHERE secondary_muscle_group = $1
`

func (q *Queries) GetExercisesBySecondaryMG(ctx context.Context, secondaryMuscleGroup sql.NullString) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getExercisesBySecondaryMG, secondaryMuscleGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PrimaryMuscleGroup,
			&i.SecondaryMuscleGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET
    updated_at = now(),
    name = $1,
    description = $2,
    primary_muscle_group = $3,
    secondary_muscle_group = $4
WHERE id = $5
RETURNING id, name, description, primary_muscle_group, secondary_muscle_group, created_at, updated_at
`

type UpdateExerciseParams struct {
	Name                 string
	Description          sql.NullString
	PrimaryMuscleGroup   sql.NullString
	SecondaryMuscleGroup sql.NullString
	ID                   uuid.UUID
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, updateExercise,
		arg.Name,
		arg.Description,
		arg.PrimaryMuscleGroup,
		arg.SecondaryMuscleGroup,
		arg.ID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrimaryMuscleGroup,
		&i.SecondaryMuscleGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
