// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: metrics.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addBodyFatPerc = `-- name: AddBodyFatPerc :one
INSERT INTO body_fat_percents (
  id,
  created_at,
  updated_at,
  user_id,
  measurement
) VALUES ( gen_random_uuid(), NOW(), NOW(), $1, $2)
  RETURNING id, user_id, measurement, created_at, updated_at
`

type AddBodyFatPercParams struct {
	UserID      uuid.UUID
	Measurement string
}

func (q *Queries) AddBodyFatPerc(ctx context.Context, arg AddBodyFatPercParams) (BodyFatPercent, error) {
	row := q.db.QueryRowContext(ctx, addBodyFatPerc, arg.UserID, arg.Measurement)
	var i BodyFatPercent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Measurement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addBodyWeight = `-- name: AddBodyWeight :one
INSERT INTO body_weights (
  id,
  created_at,
  updated_at,
  user_id,
  measurement
) VALUES ( gen_random_uuid(), NOW(), NOW(), $1, $2)
  RETURNING id, user_id, measurement, created_at, updated_at
`

type AddBodyWeightParams struct {
	UserID      uuid.UUID
	Measurement string
}

func (q *Queries) AddBodyWeight(ctx context.Context, arg AddBodyWeightParams) (BodyWeight, error) {
	row := q.db.QueryRowContext(ctx, addBodyWeight, arg.UserID, arg.Measurement)
	var i BodyWeight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Measurement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addMuscleMass = `-- name: AddMuscleMass :one
INSERT INTO muscle_masses (
  id,
  created_at,
  updated_at,
  user_id,
  measurement
) VALUES ( gen_random_uuid(), NOW(), NOW(), $1, $2)
  RETURNING id, user_id, measurement, created_at, updated_at
`

type AddMuscleMassParams struct {
	UserID      uuid.UUID
	Measurement string
}

func (q *Queries) AddMuscleMass(ctx context.Context, arg AddMuscleMassParams) (MuscleMass, error) {
	row := q.db.QueryRowContext(ctx, addMuscleMass, arg.UserID, arg.Measurement)
	var i MuscleMass
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Measurement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBodyFatPerc = `-- name: DeleteBodyFatPerc :exec
DELETE FROM body_fat_percents
  WHERE id = $1 AND user_id = $2
`

type DeleteBodyFatPercParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteBodyFatPerc(ctx context.Context, arg DeleteBodyFatPercParams) error {
	_, err := q.db.ExecContext(ctx, deleteBodyFatPerc, arg.ID, arg.UserID)
	return err
}

const deleteBodyWeight = `-- name: DeleteBodyWeight :exec
DELETE FROM body_weights
  WHERE id = $1 AND user_id = $2
`

type DeleteBodyWeightParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteBodyWeight(ctx context.Context, arg DeleteBodyWeightParams) error {
	_, err := q.db.ExecContext(ctx, deleteBodyWeight, arg.ID, arg.UserID)
	return err
}

const deleteMuscleMass = `-- name: DeleteMuscleMass :exec
DELETE FROM muscle_masses
  WHERE id = $1 AND user_id = $2
`

type DeleteMuscleMassParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMuscleMass(ctx context.Context, arg DeleteMuscleMassParams) error {
	_, err := q.db.ExecContext(ctx, deleteMuscleMass, arg.ID, arg.UserID)
	return err
}

const getAllBodyFatPercs = `-- name: GetAllBodyFatPercs :many
SELECT id, user_id, measurement, created_at, updated_at FROM body_fat_percents
  WHERE user_id = $1
`

func (q *Queries) GetAllBodyFatPercs(ctx context.Context, userID uuid.UUID) ([]BodyFatPercent, error) {
	rows, err := q.db.QueryContext(ctx, getAllBodyFatPercs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BodyFatPercent
	for rows.Next() {
		var i BodyFatPercent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Measurement,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllBodyWeights = `-- name: GetAllBodyWeights :many
SELECT id, user_id, measurement, created_at, updated_at FROM body_weights
  WHERE user_id = $1
`

func (q *Queries) GetAllBodyWeights(ctx context.Context, userID uuid.UUID) ([]BodyWeight, error) {
	rows, err := q.db.QueryContext(ctx, getAllBodyWeights, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BodyWeight
	for rows.Next() {
		var i BodyWeight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Measurement,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMuscleMasses = `-- name: GetAllMuscleMasses :many
SELECT id, user_id, measurement, created_at, updated_at FROM muscle_masses
  WHERE user_id = $1
`

func (q *Queries) GetAllMuscleMasses(ctx context.Context, userID uuid.UUID) ([]MuscleMass, error) {
	rows, err := q.db.QueryContext(ctx, getAllMuscleMasses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MuscleMass
	for rows.Next() {
		var i MuscleMass
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Measurement,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBodyFatPerc = `-- name: UpdateBodyFatPerc :one
UPDATE body_fat_percents
  SET measurement = $1,
      updated_at = NOW()
  WHERE id = $2 AND user_id = $3
  RETURNING id, user_id, measurement, created_at, updated_at
`

type UpdateBodyFatPercParams struct {
	Measurement string
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateBodyFatPerc(ctx context.Context, arg UpdateBodyFatPercParams) (BodyFatPercent, error) {
	row := q.db.QueryRowContext(ctx, updateBodyFatPerc, arg.Measurement, arg.ID, arg.UserID)
	var i BodyFatPercent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Measurement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBodyWeight = `-- name: UpdateBodyWeight :one
UPDATE body_weights
  SET measurement = $1,
      updated_at = NOW()
  WHERE id = $2 AND user_id = $3 
  RETURNING id, user_id, measurement, created_at, updated_at
`

type UpdateBodyWeightParams struct {
	Measurement string
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateBodyWeight(ctx context.Context, arg UpdateBodyWeightParams) (BodyWeight, error) {
	row := q.db.QueryRowContext(ctx, updateBodyWeight, arg.Measurement, arg.ID, arg.UserID)
	var i BodyWeight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Measurement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMuscleMass = `-- name: UpdateMuscleMass :one
UPDATE muscle_masses
  SET measurement = $1,
      updated_at = NOW()
  WHERE id = $2 AND user_id = $3
  RETURNING id, user_id, measurement, created_at, updated_at
`

type UpdateMuscleMassParams struct {
	Measurement string
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateMuscleMass(ctx context.Context, arg UpdateMuscleMassParams) (MuscleMass, error) {
	row := q.db.QueryRowContext(ctx, updateMuscleMass, arg.Measurement, arg.ID, arg.UserID)
	var i MuscleMass
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Measurement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
