// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workouts_exercises.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addExerciseToWorkout = `-- name: AddExerciseToWorkout :one
INSERT INTO workouts_exercises (
    id,
    workout_id,
    exercise_id,
    sets_planned,
    reps_per_set_planned,
    sets_completed,
    reps_per_set_completed,
    weights_planned_lbs,
    weights_completed_lbs,
    updated_at,
    created_at
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    now(),
    now()
) RETURNING id, workout_id, exercise_id, sets_planned, reps_per_set_planned, sets_completed, reps_per_set_completed, weights_planned_lbs, weights_completed_lbs, date_completed, updated_at, created_at
`

type AddExerciseToWorkoutParams struct {
	WorkoutID           uuid.UUID
	ExerciseID          uuid.UUID
	SetsPlanned         int32
	RepsPerSetPlanned   []int32
	SetsCompleted       int32
	RepsPerSetCompleted []int32
	WeightsPlannedLbs   []int32
	WeightsCompletedLbs []int32
}

func (q *Queries) AddExerciseToWorkout(ctx context.Context, arg AddExerciseToWorkoutParams) (WorkoutsExercise, error) {
	row := q.db.QueryRowContext(ctx, addExerciseToWorkout,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.SetsPlanned,
		pq.Array(arg.RepsPerSetPlanned),
		arg.SetsCompleted,
		pq.Array(arg.RepsPerSetCompleted),
		pq.Array(arg.WeightsPlannedLbs),
		pq.Array(arg.WeightsCompletedLbs),
	)
	var i WorkoutsExercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetsPlanned,
		pq.Array(&i.RepsPerSetPlanned),
		&i.SetsCompleted,
		pq.Array(&i.RepsPerSetCompleted),
		pq.Array(&i.WeightsPlannedLbs),
		pq.Array(&i.WeightsCompletedLbs),
		&i.DateCompleted,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const exercisesForWorkout = `-- name: ExercisesForWorkout :many
SELECT
    workouts_exercises.id, workouts_exercises.workout_id, workouts_exercises.exercise_id, workouts_exercises.sets_planned, workouts_exercises.reps_per_set_planned, workouts_exercises.sets_completed, workouts_exercises.reps_per_set_completed, workouts_exercises.weights_planned_lbs, workouts_exercises.weights_completed_lbs, workouts_exercises.date_completed, workouts_exercises.updated_at, workouts_exercises.created_at,
    exercises.id, exercises.name, exercises.description, exercises.primary_muscle_group, exercises.secondary_muscle_group, exercises.created_at, exercises.updated_at
FROM workouts_exercises
JOIN exercises
    ON workouts_exercises.exercise_id = exercises.id
WHERE workouts_exercises.workout_id = $1
`

type ExercisesForWorkoutRow struct {
	WorkoutsExercise WorkoutsExercise
	Exercise         Exercise
}

func (q *Queries) ExercisesForWorkout(ctx context.Context, workoutID uuid.UUID) ([]ExercisesForWorkoutRow, error) {
	rows, err := q.db.QueryContext(ctx, exercisesForWorkout, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExercisesForWorkoutRow
	for rows.Next() {
		var i ExercisesForWorkoutRow
		if err := rows.Scan(
			&i.WorkoutsExercise.ID,
			&i.WorkoutsExercise.WorkoutID,
			&i.WorkoutsExercise.ExerciseID,
			&i.WorkoutsExercise.SetsPlanned,
			pq.Array(&i.WorkoutsExercise.RepsPerSetPlanned),
			&i.WorkoutsExercise.SetsCompleted,
			pq.Array(&i.WorkoutsExercise.RepsPerSetCompleted),
			pq.Array(&i.WorkoutsExercise.WeightsPlannedLbs),
			pq.Array(&i.WorkoutsExercise.WeightsCompletedLbs),
			&i.WorkoutsExercise.DateCompleted,
			&i.WorkoutsExercise.UpdatedAt,
			&i.WorkoutsExercise.CreatedAt,
			&i.Exercise.ID,
			&i.Exercise.Name,
			&i.Exercise.Description,
			&i.Exercise.PrimaryMuscleGroup,
			&i.Exercise.SecondaryMuscleGroup,
			&i.Exercise.CreatedAt,
			&i.Exercise.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
