// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workouts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (
    id,
    created_at,
    updated_at,
    user_id,
    title,
    description,
    duration_minutes,
    planned_date
) VALUES (
      gen_random_uuid(),
      NOW(),
      NOW(),
      $1,
      $2,
      $3,
      $4,
      $5
  ) RETURNING id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at
`

type CreateWorkoutParams struct {
	UserID          uuid.UUID
	Title           string
	Description     sql.NullString
	DurationMinutes int32
	PlannedDate     time.Time
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.PlannedDate,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.PlannedDate,
		&i.DateCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllUserWorkouts = `-- name: GetAllUserWorkouts :many
SELECT id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at FROM workouts
    WHERE user_id = $1
`

func (q *Queries) GetAllUserWorkouts(ctx context.Context, userID uuid.UUID) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.PlannedDate,
			&i.DateCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
