// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_templates.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getAllWorkoutTemplates = `-- name: GetAllWorkoutTemplates :many
SELECT
    id,
    template_name,
    description,
    exercise_set_reps,
    duration_minutes
FROM workout_templates
`

type GetAllWorkoutTemplatesRow struct {
	ID              uuid.UUID
	TemplateName    string
	Description     string
	ExerciseSetReps json.RawMessage
	DurationMinutes int32
}

func (q *Queries) GetAllWorkoutTemplates(ctx context.Context) ([]GetAllWorkoutTemplatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWorkoutTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWorkoutTemplatesRow
	for rows.Next() {
		var i GetAllWorkoutTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateName,
			&i.Description,
			&i.ExerciseSetReps,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
