// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (
    id,
    created_at,
    updated_at,
    user_id,
    title,
    description,
    duration_minutes,
    planned_date
) VALUES (
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at
`

type CreateWorkoutParams struct {
	UserID          uuid.UUID
	Title           string
	Description     sql.NullString
	DurationMinutes int32
	PlannedDate     time.Time
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.PlannedDate,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.PlannedDate,
		&i.DateCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllUserWorkouts = `-- name: DeleteAllUserWorkouts :exec
DELETE FROM workouts
WHERE user_id = $1
`

func (q *Queries) DeleteAllUserWorkouts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserWorkouts, userID)
	return err
}

const deleteCompletedWorkout = `-- name: DeleteCompletedWorkout :one
WITH deleted AS (
    DELETE FROM workouts WHERE workouts.id = $1 AND workouts.user_id = $2 RETURNING workouts.user_id
)
SELECT COUNT(*) FROM workouts WHERE workouts.user_id = $2 AND workouts.date_completed IS NOT NULL
`

type DeleteCompletedWorkoutParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCompletedWorkout(ctx context.Context, arg DeleteCompletedWorkoutParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteCompletedWorkout, arg.ID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUpcomingWorkout = `-- name: DeleteUpcomingWorkout :one
WITH deleted AS (
    DELETE FROM workouts WHERE workouts.id = $1 AND workouts.user_id = $2 RETURNING workouts.user_id
)
SELECT COUNT(*) FROM workouts WHERE workouts.user_id = $2 AND workouts.date_completed IS NULL
`

type DeleteUpcomingWorkoutParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUpcomingWorkout(ctx context.Context, arg DeleteUpcomingWorkoutParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteUpcomingWorkout, arg.ID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts
WHERE id = $1 AND user_id = $2
`

type DeleteWorkoutParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkout, arg.ID, arg.UserID)
	return err
}

const getAllUserWorkouts = `-- name: GetAllUserWorkouts :many
SELECT id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at FROM workouts
WHERE user_id = $1
`

func (q *Queries) GetAllUserWorkouts(ctx context.Context, userID uuid.UUID) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.PlannedDate,
			&i.DateCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedUserWorkouts = `-- name: GetCompletedUserWorkouts :many
SELECT id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at FROM workouts
WHERE user_id = $1 AND date_completed IS NOT NULL
ORDER BY date_completed DESC
`

func (q *Queries) GetCompletedUserWorkouts(ctx context.Context, userID uuid.UUID) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedUserWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.PlannedDate,
			&i.DateCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingUserWorkouts = `-- name: GetUpcomingUserWorkouts :many
SELECT id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at FROM workouts
WHERE user_id = $1 AND date_completed IS NULL
ORDER BY planned_date ASC
`

func (q *Queries) GetUpcomingUserWorkouts(ctx context.Context, userID uuid.UUID) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingUserWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.PlannedDate,
			&i.DateCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at FROM workouts
WHERE id = $1 AND user_id = $2
`

type GetWorkoutByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetWorkoutByID(ctx context.Context, arg GetWorkoutByIDParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByID, arg.ID, arg.UserID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.PlannedDate,
		&i.DateCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkout = `-- name: UpdateWorkout :one
UPDATE workouts
SET
    updated_at = now(),
    title = $1,
    description = $2,
    duration_minutes = $3,
    planned_date = $4,
    date_completed = $5
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, title, description, duration_minutes, planned_date, date_completed, created_at, updated_at
`

type UpdateWorkoutParams struct {
	Title           string
	Description     sql.NullString
	DurationMinutes int32
	PlannedDate     time.Time
	DateCompleted   sql.NullTime
	ID              uuid.UUID
	UserID          uuid.UUID
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, updateWorkout,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.PlannedDate,
		arg.DateCompleted,
		arg.ID,
		arg.UserID,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.PlannedDate,
		&i.DateCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
